= Arquillian Graphene 2
:asciidoctor-source: https://raw.githubusercontent.com/arquillian/arquillian-cube/master/docs
:numbered:
:sectlink:
:sectanchors:
:sectid:
:source-language: java
:source-highlighter: coderay
:sectnums:
:icons: font
:toc: left

*'`Robust Functional Tests leveraging WebDriver with flavour of sexy AJAX-ready API`'*

[[documentation]]
== Documentation

Graphene 2 project is designed as a set of extensions for
http://docs.seleniumhq.org/[Selenium WebDriver] project focused on rapid
development and usability in Java environment.

Extensive documentation is available in the docs section.

* link:{asciidoctor-source}/graphene-introduction.adoc[Graphene Introduction] walks you through the project
information, elaborating what it is about and why use it.
* If you want to quickly get started with sample tests and use-cases,
have a look at link:{asciidoctor-source}/getting-started-guide.adoc[Getting Started Guide] to see how to setup project
and use it to write robust tests.
* Have a look at link:{asciidoctor-source}/graphene-configuration.adoc[Graphene Configuration]
for all your configuration needs and details of different properties available at
your disposal.
* link:{asciidoctor-source}/graphene-utility-class.adoc[Graphene Utility Class] enlists the library of static methods
that can be directly used from tests.
* For detailed reading of the different features available to you out of
the box, don't forget to have a look at:
** link:{asciidoctor-source}/waiting-API.adoc[Waiting API]
** link:{asciidoctor-source}/request-guards.adoc[Request Guards]
** link:{asciidoctor-source}/page-abstractions.adoc[Page Abstractions]
** link:{asciidoctor-source}/location-strategies.adoc[Location Strategies]
** link:{asciidoctor-source}/dependency-injection.adoc[Dependency Injection]
** link:{asciidoctor-source}/parallel-browsers.adoc[Parallel Browsers]
** link:{asciidoctor-source}/javaScript-interface.adoc[JavaScript Interface]
** link:{asciidoctor-source}/tips-&-tricks.adoc[Tips and Tricks]
** link:{asciidoctor-source}/advanced-techniques.adoc[Advanced Techniques]

[[getting-started]]
=== Getting Started

Apart from the documentation available here, there is also a
comprehensive guide
http://arquillian.org/guides/functional_testing_using_graphene/[Functional
Testing using Drone and Graphene] to help you leverage the benefits of
Graphene for writing robust functional tests.

[[contributing]]
== Contributing

Community contributions are essential for maintaining the vitality of
the Arquillian project.

Contributing to the project helps to deliver functionality you need and
allows you to share your code with other contributors and users.

We want to keep it as easy as possible to contribute your changes and we
will work hard to deliver your contributions in an upcoming release.

Please refer to
https://github.com/arquillian/arquillian-graphene/blob/master/CONTRIBUTING.md[How
to Contribute] to find related instructions.

[[building-the-project]]
== Building the Project

[[prerequisities]]
=== Prerequisites

* JDK 1.6+
* Maven 3.0.3+

[[how-to-build-project]]
=== How-to build project

....
mvn clean install
....

[[running-integration-tests]]
=== Running Integration Tests

....
mvn clean install

cd ftest/
mvn clean verify -Dbrowser=firefox
mvn clean verify -Dbrowser=chrome
mvn clean verify -Dbrowser=phantomjs
....
