version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.1
jobs:
  build:
    parameters:
      jdk-version:
        type: string
      browser:
        type: string
    working_directory: /home/circleci/circleci-arquillian
    docker:
      - image: cimg/openjdk:<< parameters.jdk-version >>-browsers
    resource_class: large
    steps:
      - run: cd /tmp
      - browser-tools/install-browser-tools
      - run: cd "${CIRCLE_WORKING_DIRECTORY}"
      - checkout
      - restore_cache:
          key: circleci-arquillian-graphene-{{ checksum "pom.xml" }}
      - run: ./mvnw verify -q -U -DskipTests
      - run: ./mvnw verify -Dbrowser=<< parameters.browser >>
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-arquillian-graphene-{{ checksum "pom.xml" }}

workflows:
  version: 2.1
  circleci_build:
    jobs:
      - build:
          name: build-jdk-<< matrix.jdk-version >>-<< matrix.browser >>
          matrix:
            parameters:
              jdk-version: ["8.0"]
              browser: [ "firefox", "chrome" ]

