Advanced Techniques - Graphene 2
================================

[[advanced-techniques]]
Advanced Techniques
-------------------

* link:#53118028[Graphene Context and Proxy]
* link:#53117996[Page Extensions]
* link:#67241483[Graphene Interceptors]

[[53118028]]
[[graphene-context-and-proxy]]
Graphene Context and Proxy
--------------------------

Graphene stores WebDriver instance in the thread-local context,
distinguished by browser qualifier.

It enables to write framework-like features where context of the browser
is injected just when you need it:

[[53118028_GrapheneContextandProxy-Accessing]]
[[accessing]]
Accessing
~~~~~~~~~

To access a browser session, you can obtain proxy of the context,

which is proxy object which delegates the methods you call on an
instance which is at the time available in the context of current
thread.

The most generic form is obtaining instance of WebDriver:

[source,java]
----
WebDriver browser = GrapheneContext.getContextFor(Default.class).getWebDriver();
----

The Default.class representas a browser's qualifier - in this case we
are requesting default browser (when no qualifier is specified on Drone
instances). Read more
in https://docs.jboss.org/author/display/ARQGRA2/Parallel+browsers[Parallel
browsers].

You can also use alternative methods, most notably the method which
provides proxy object implementing given extension interfaces:

[source,java]
----
JavascriptExecutor executor = (JavascriptExecutor) GrapheneContext.getContextFor(Default.class).getWebDriver(JavascriptExecutor.class)
----

[[53117996]]
[[page-extensions]]
Page Extensions
---------------

[[53117996_PageExtensions-]]
[[the-page-extensions-spi-is-not-yet-available-for-public-use-we-discourage-to-use-it-yet]]
The Page Extensions SPI is not yet available for public use, we
discourage to use it yet

Page extensions mechanism provides a way to easily install your
JavaScript code into the page. Page extensions are used mainly in
cooperation with
https://docs.jboss.org/author/display/ARQGRA2/JavaScript+Interface[JavaScript
Interface], but they can be used independently too.

[[53117996_PageExtensions-BasicUsage]]
[[basic-usage]]
Basic Usage
~~~~~~~~~~~

[[53117996_PageExtensions-OwnExtensions]]
[[own-extensions]]
Own Extensions
^^^^^^^^^^^^^^

Extensions has to implement `PageExtension` interface to define:

* name,
* JavaScript code to be executed when the extension is installed,
* JavaScript code returning true if the extension is already installed,
false otherwise,
* dependencies.

[[53117996_PageExtensions-SPI]]
[[spi]]
SPI
+++

To provide your own extensions you can use `PageExtensionProvider`
service containing the following method:

[source,java]
----
// returns a list of extension for the given test class
List<PageExtension> getPageExtensions(TestClass testClass);
----

[[53117996_PageExtensions-Registry]]
[[registry]]
Registry
++++++++

The second way to provide your own extension is to use
`PageExtensionRegistry`:

[source,java]
----
PageExtension pageExtension = new MyCoolPageExtension(...);
GraphenePageExtensionsContext.getRegistryProxy().register(pageExtension);
----

The registry can be also used to check whether the given extension is
available:

[source,java]
----
// returns page extension with the given name, or null if there is no extension with the given name
GraphenePageExtensionsContext.getRegistryProxy().getExtension("my cool extension");
----

[[53117996_PageExtensions-Installation]]
[[installation]]
Installation
^^^^^^^^^^^^

Each extensions is defined with its name. When you want to install the
extension just ask for its installator and install it. All defined
dependencies will be installed too. When the extension is detected as
already installed, the installation is skipped (including installation
of all dependencies).

[source,java]
----
GraphenePageExtensionsContext.getInstallatorProviderProxy().installator("extension name").install();
----

The installator is available only for extensions already registered via
SPI or registry.

When a page is reloaded, all injected JavaScript code is lost, so the
extension has to be installed again.

[[67241483]]
[[graphene-interceptors]]
Graphene Interceptors
---------------------

[[67241483_GrapheneInterceptors-]]
[[interceptors-are-not-officially-part-of-2.0-and-thus-they-are-not-available-for-production-use-yet.]]
Interceptors are not officially part of 2.0 and thus they are not
available for production use yet.

Graphene Interceptors concept is inspired by Java EE Interceptors
feature. It is a way how to create interceptor classes and methods that
interpose on method invocations.

[[67241483_GrapheneInterceptors-Basicusage]]
[[basic-usage-1]]
Basic usage
~~~~~~~~~~~

An example of interceptor usage can be a need to take a screenshot of
the browser window and its saving after the every method invocation on
the injected `WebDriver` instance. Building an interceptor is simply
matter of writing a Java class that implements
the `org.jboss.arquillian.graphene.proxy.Interceptor` interface.

[source,java]
----
import org.jboss.arquillian.graphene.proxy.Interceptor;
import org.jboss.arquillian.graphene.proxy.InvocationContext;
import org.foo.bar.ScreenshotTaker;

public class ScreenshotTakerInterceptor implements Interceptor {

    @Override
    public Object intercept(final InvocationContext context) {
        ScreenshotTaker.takeScreenshot();
        return context.invoke();
    }
}
----

Each implementor must satisfy, that in the `intercept` method body will
be called at least once method from current context:
`InvocationContext#invoke()`.

Secondly, the interceptor needs to be registered. Currently this can be
achieved like in the following listing:

[source,java]
----
@Drone
WebDriver browser;

public void beforeSomething() {
    GrapheneProxyInstance proxy = (GrapheneProxyInstance) browser;
    proxy.registerInterceptor(new ScreenshotTakerInterceptor());
}
----

In the example above the interceptor was registered to the `WebDriver`
instance, thus all method invocations on that object will be
intercepted. Note that you can register the interceptor to any object
which can be casted to `GrapheneProxyInstance`. For instance to Page
Objects.

You can use `GrapheneProxyInstance#unregisterInterceptor` method to
unregister previously registered interceptor.

Have an inspiration in `StaleElementInterceptor`
(https://github.com/arquillian/arquillian-graphene/blob/master/impl/src/main/java/org/jboss/arquillian/graphene/enricher/StaleElementInterceptor.java[here]),
Graphene way of protecting the elements from
`StaleElementReferenceException`.
