Parallel browsers - Graphene 2
==============================

[[parallel-browsers]]
Parallel Browsers
-----------------

It is a way to use multiple `WebDriver` instances in one test.

[[73138633_Parallelbrowsers-Usage]]
[[usage]]
Usage
~~~~~

[[73138633_Parallelbrowsers-]]
[[section]]

Consider testing of the server push functionality. More particularly a
scenario where:

1.  You make an update to a server from a FireFox browser.
2.  The server will push the update to all registered listeners.
3.  You want to check that client loaded in the Chrome will receive the
update as well.

The Graphene support for testing of the above will look like:

[source,java]
----
@Browser1
@Drone
private WebDriver browser1;

@Browser2
@Drone
private WebDriver browser2;

public void testServerPushFromFirefoxToChromeAfterRegistration() {
    browser1.get(“http://localhost:8080/myApp”);
    browser2.get(“http://localhost:8080/myApp”);

    formFragment.registerUser(new User(“John”), browser1);
    registeredUsers.assertContains(“John”, browser2);
}
----

`@Browser1` and `@Browser2` annotations are qualifiers, similar concept
as in CDI. Declaration of one of them may look like:

[source,java]
----
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import org.jboss.arquillian.drone.api.annotation.Qualifier;

@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.FIELD, ElementType.PARAMETER })
@Qualifier
public @interface Browser1 {

}
----

You can configure these browsers in `arquillian.xml`:

[source,xml]
----
<extension qualifier="webdriver-browser1">
  <property name="browser">firefox</property>
</extension>
<extension qualifier="webdriver-browser2">
  <property name="browser">chrome</property>
</extension>
----

[[73138633_Parallelbrowsers-UsingPageAbstractionswithMultipleBrowsers]]
[[using-page-abstractions-with-multiple-browsers]]
Using Page Abstractions with Multiple Browsers
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

When you have multiple browser instances, lets say annotated with
qualifiers @Browser1 and @Browser2, and want to inject a page
abstraction, you have to specify against which browser instance you want
to get it resolved:

[source,java]
----
@Browser1 @Drone WebDriver browser1;
@Browser2 @Drone WebDriver browser2;

@Browser1 @FindBy(id = "login-box") private LoginFragment loginFragment;
@Browser2 HomePage page;
----

Without having that fragment annotated with browser qualifier, Graphene
will resolve it against @Default browser instance.
